data:
  batch_size: 256
  color_jitter_strength: 0.0
  crop_scale:
    - 0.3
    - 1.0
  crop_size: 126
  image_folder: /kaggle/working/Data/Dataset_normalized.h5
  num_workers: 2
  pin_mem: true
  root_path: /kaggle/working/Dataset_normalized.h5
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  folder: /kaggle/working/Logging/vit_base
  write_tag: ijepa_cms
mask:
  allow_overlap: false
  aspect_ratio:
    - 0.75
    - 1.5
  enc_mask_scale:
    - 0.85
    - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 14
  pred_mask_scale:
    - 0.15
    - 0.2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_base
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: true
optimization:
  ema:
    - 0.996
    - 1.0
  epochs: 30
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 1
  weight_decay: 0.04
